### ISSUE TITLE
Quantization counting

### ISSUE THREAD

**Issue by micronet-challenge-submissions** [Lee-Gihun/MicroNet_OSI-AI#4]
In your REAMDE, you cut the number of math operations in half from 16-bit quantization. Are you taking the "freebie" quantization discount? If so, additions are counted as if they are performed in 32-bit and you'll need to take this into account in your scoring.

Trevor

**Comment by Lee-Gihun** [comment]
To best our knowledge, 'freebie quantization discount' means that the parameter storage and operations are actually 32-bit but can be regarded as 16-bit for counting, applying 32-bit to addition operation.

But in our structure, all samples & parameters are actually 16-bit floating point data type of Pytorch. So we applied 16-bit for both multiplication and addition operations.

If you confirm that this approach is correct, let me close this issue :)

Team OSI-AI

**Comment by micronet-challenge-submissions** [comment]
Interesting! Thanks for the clarification. 

One thing that we'll need to confirm is that the underlying PyTorch operator is truly doing 16-bit additions. It's common to perform what's called "pseduo-fp16", where the inputs are 16-bits but the arithmetic is performed in 32-bits inside the matmul/conv kernels. Could you point us at where you set the precision for these operations?

**Comment by micronet-challenge-submissions** [comment]
For example, if you're calling convolutions on GPU, it looks like PyTorch is running a pseudo-fp16 convolution.

Here's and old issue where someone had trouble with true FP16 convolutions:
https://github.com/pytorch/pytorch/issues/520

Here's an old pull request that made the change:
https://github.com/pytorch/pytorch/pull/668

And here's where they set the math type to FP32 when you call and FP16 convolution in today's PyTorch:
https://github.com/pytorch/pytorch/blob/2bcbc15023c957837c0c3715a217027d4a006b70/aten/src/ATen/cudnn/Descriptors.h#L155

**Comment by Lee-Gihun** [comment]
Oh we just checked that you're right about the 16-bit operation underlying Pytorch. It seems the 16-bit is always converted to 32-bit. (the last link you mentioned)

We'd like to temporary withdrawal our submission until we verify the full score and adapt the model structure following the score criteria. Is this counted as 'submission' among the allowed 3 times submission?

thank you for clarify the criteria.

**Comment by micronet-challenge-submissions** [comment]
No, it's totally fine if you don't want to count this as one of your three
submissions. Let us know when you're ready to submit!

Trevor
