### ISSUE TITLE
Official Review

### ISSUE THREAD

**Issue by micronet-challenge-submissions** [Lee-Gihun/MicroNet_OSI-AI#7]
Hello! I've validated your trained checkpoint and everything checks out! If you can update the batch norm bias counting we should be all set!

Trevor

**Comment by raymin0223** [comment]
@micronet-challenge-submissions 

Now we update the batch norm bias counting.
Our final score is on `README.md`.

Thanks!
Team OSI-AI

**Comment by micronet-challenge-submissions** [comment]
Thanks for the update!

Trevor
